  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.12.0 # 
    container_name: mealie
    restart: unless-stopped
    ports:
        - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /mnt/drive/Mealie:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Budapest
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: 192.168.0.122:9925